spring.application.name=semana1

# Configuracion Database Oracle (wallet)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=${DB_TNS_ADMIN}

# Inicialización BD
spring.sql.init.mode=always
spring.sql.init.platform=oracle

# Archivos de entrada
app.input.cuentas-anuales=classpath:cuentas_anuales.csv
app.input.intereses=classpath:intereses.csv
app.input.transacciones=classpath:transacciones.csv

# Inicializacion de tablas de Spring Batch
spring.batch.jdbc.initialize-schema=always

