spring.application.name=semana1

## Job en ejecución
spring.batch.job.name=

# Configuracion Database Oracle (wallet)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=${DB_TNS_ADMIN}

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000

# HTTPS
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:https.p12
server.ssl.key-store-password=https123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=https

# Inicialización BD
spring.sql.init.mode=never
spring.sql.init.platform=oracle

# Archivos de entrada
app.input.cuentas-anuales=classpath:cuentas_anuales.csv
app.input.intereses=classpath:intereses.csv
app.input.transacciones=classpath:transacciones.csv

# Inicializacion de tablas de Spring Batch
spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=false

# ==PARAMETRIZACION CONFIG DE MULTITHREAD==

# =========================
# Movimiento Anual
# =========================
app.movimiento.chunk-size=100
app.movimiento.core-pool-size=25
app.movimiento.max-pool-size=35
app.movimiento.queue-capacity=50

# =========================
# Transacciones
# =========================
app.transaccion.chunk-size=100
app.transaccion.core-pool-size=25
app.transaccion.max-pool-size=35
app.transaccion.queue-capacity=50

# =========================
# Cuenta Intereses
# =========================
app.cuenta-interes.chunk-size=20
app.cuenta-interes.core-pool-size=4
app.cuenta-interes.max-pool-size=8
app.cuenta-interes.queue-capacity=50

# periodo para cuenta interes
app.intereses.periodo=2026-08





