CREATE TABLE movimientos_anuales (
    movimiento_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id NUMBER NOT NULL,
    fecha DATE NOT NULL,
    transaccion VARCHAR2(20) NOT NULL,
    monto NUMBER(15,2) NOT NULL,
    descripcion VARCHAR2(200) NOT NULL
);

CREATE TABLE cuentas_intereses (
    cuenta_interes_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id NUMBER NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    saldo_inicial NUMBER(15,2) NOT NULL,
    tipo VARCHAR2(20) NOT NULL,
    interes_aplicado NUMBER(15,2) NOT NULL,
    saldo_final NUMBER(15,2) NOT NULL
);

CREATE TABLE transacciones_diarias (
    transaccion_id NUMBER PRIMARY KEY,
    fecha DATE NOT NULL,
    monto NUMBER(15,2) NOT NULL,
    tipo VARCHAR2(20) NOT NULL,
    anomalia NUMBER(1) NOT NULL,
    motivo_anomalia VARCHAR2(200)
);